apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: app-service
  template:
    metadata:
      labels:
        app: app-service
    spec:
      containers:
        - name: app-service
          image: trungnd01/app-service:latest
          ports:
            - containerPort: 8080
